#datasource specific properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomproductdb
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#jps specific properties
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#add driver nae=me while using docker