server:
  port: 8081


spring:
 application:
  name: product-catalog
#datasource specific properties 
 datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ekartproductdb
#jpa properties
 jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  

