server:
  port: 8084


spring:
 application:
  name: product-catalog
##datasource specific properties 
# datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/ekartproductdb
##jpa properties
# jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
 config:
   import: configserver:http://localhost:8888
 profiles:
    active:
    - dev

message: Goodbye   
  #http://localhost:8888/product-catalog.yml   



